apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts
  labels:
    app: accounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts
  template:
    metadata:
      labels:
        app: accounts
    spec:
      containers:
        - name: accounts
          image: achrefloussaief101/accounts
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_APPLICATION_NAME
              value: accounts
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING_CONFIG_IMPORT
              value: optional:configserver:http://configserver:8071/
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eurekaserver:8761/eureka/
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/eazybank_accounts
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
            - name: SERVER_ADDRESS
              value: 0.0.0.0
            - name: SERVER_PORT
              value: "8080"
      restartPolicy: Always
