apiVersion: apps/v1
kind: Deployment
metadata:
  name: loans
  labels:
    app: loans
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loans
  template:
    metadata:
      labels:
        app: loans
    spec:
      containers:
        - name: loans
          image: achrefloussaief101/loans
          ports:
            - containerPort: 9001
              name: http
          env:
            - name: SPRING_APPLICATION_NAME
              value: loans
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING_CONFIG_IMPORT
              value: optional:configserver:http://configserver:8071/
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eurekaserver:8761/eureka/
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/eazybank_loans
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
            - name: SERVER_ADDRESS
              value: 0.0.0.0
            - name: SERVER_PORT
              value: "9001"
      restartPolicy: Always