apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-initdb
  labels:
    app: postgres
data:
  init.sql: |
    CREATE DATABASE eazybank_accounts;
    CREATE DATABASE eazybank_cards;
    CREATE DATABASE eazybank_loans;
