version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  configserver:
    build:
      context: ./configserver
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: native
      ENCRYPT_KEY: 45D81EC1EF61DF9AD8D3E5BB397F9
    volumes:
      - ./eazybytes-config:/config-repo
    ports:
      - 8071:8071
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent http://localhost:8071/actuator/health | grep UP || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  eurekaserver:
    build:
      context: ./eurekaserver
      dockerfile: Dockerfile
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: optional:configserver:http://configserver:8071/
      SERVER_PORT: 8761
      SERVER_ADDRESS: 0.0.0.0
    ports:
      - 8761:8761

  accounts:
    build:
      context: ./accounts
      dockerfile: Dockerfile
    depends_on:
      - configserver
      - eurekaserver
      - postgres
    environment:
      SPRING_APPLICATION_NAME: accounts
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: optional:configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/eazybank_accounts
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SERVER_ADDRESS: 0.0.0.0
      SERVER_PORT: 8080
    ports:
      - 8080:8080

  cards:
    build:
      context: ./cards
      dockerfile: Dockerfile
    depends_on:
      - configserver
      - eurekaserver
      - postgres
    environment:
      SPRING_APPLICATION_NAME: cards
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: optional:configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/eazybank_cards
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SERVER_ADDRESS: 0.0.0.0
      SERVER_PORT: 9000
    ports:
      - 9000:9000

  loans:
    build:
      context: ./loans
      dockerfile: Dockerfile
    depends_on:
      - configserver
      - eurekaserver
      - postgres
    environment:
      SPRING_APPLICATION_NAME: loans
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: optional:configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/eazybank_loans
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SERVER_ADDRESS: 0.0.0.0
      SERVER_PORT: 9001
    ports:
      - 9001:9001

volumes:
  postgres_data: {}
