spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true

  cloud:
    config:
      enabled: false

# Optional: Remove this line if you're not using a config server in tests
# Or keep it if you actually want to test config-server-based imports
#  config:
#    import: "optional:configserver:http://localhost:8071/"

# ✅ Fix: Add the missing placeholder to avoid runtime failure
build:
  version: 0.0.1-SNAPSHOT
