server:
  port: 9001

spring:
  application:
    name: loans
  profiles:
    active: prod
  config:
    import: optional:configserver:http://configserver:8071
    fail-fast: true
    retry:
      initial-interval: 2000
      max-attempts: 6
      multiplier: 1.5
  datasource:
    url: jdbc:postgresql://postgres:5432/eazybank_loans
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka/

info:
  app:
    name: "loans"
    description: "Eazy Bank Loans Application"
    version: "1.0.0"

build:
  version: 1.0.0
