#cloud-config
package_update: true
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gpg
  - containerd

write_files:
  - path: /etc/kubernetes/kubeadmn-custom.yaml
    content: |
      apiVersion: kubeadm.k8s.io/v1beta3
      kind: InitConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
      ---
      apiVersion: kubeadm.k8s.io/v1beta3
      kind: ClusterConfiguration
      apiServer:
        certSANs:
          - "REPLACE_PUBLIC_IP"
      controllerManager:
        extraArgs:
          cloud-provider: external
      networking:
        podSubnet: "192.168.0.0/16"

runcmd:
  - sed -i "s/REPLACE_PUBLIC_IP/$(curl -s ifconfig.me)/g" /etc/kubernetes/kubeadmn-custom.yaml
  - kubeadm init --config=/etc/kubernetes/kubeadmn-custom.yaml
  - mkdir -p /home/azureuser/.kube
  - cp -i /etc/kubernetes/admin.conf /home/azureuser/.kube/config
  - chown azureuser:azureuser /home/azureuser/.kube/config
  - su - azureuser -c "kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml"