server:
  port: 8080

spring:
  application:
    name: configserver
  cloud:
    config:
      fail-fast: true
      retry:
        maxAttempts: 6
        initialInterval: 2000
        multiplier: 1.5

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eurekaserver:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
